-- ====================================================
-- RESET DO BANCO - Remove tabelas existentes (seguro)
-- ====================================================
BEGIN
  FOR t IN (SELECT table_name FROM user_tables) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE "' || t.table_name || '" CASCADE CONSTRAINTS';
  END LOOP;
END;
/
-- ====================================================
-- SEQUENCES
-- ====================================================

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE ITEM_CARDAPIO_SEQ';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE PEDIDO_SEQ';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE PEDIDO_ITEM_SEQ';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE SEQUENCE ITEM_CARDAPIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PEDIDO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PEDIDO_ITEM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ====================================================
-- TABELAS
-- ====================================================

CREATE TABLE ITEM_CARDAPIO (
  ID_ITEM         NUMBER PRIMARY KEY,
  NOME            VARCHAR2(255) NOT NULL,
  DESCRICAO       VARCHAR2(500),
  PRECO           NUMBER(10,2) NOT NULL,
  CATEGORIA       VARCHAR2(50),
  DISPONIVEL      NUMBER(1) DEFAULT 1,
  IMAGEM_URL      VARCHAR2(500)
);

CREATE TABLE PEDIDO (
  ID_PEDIDO       NUMBER PRIMARY KEY,
  ID_COMANDA      NUMBER NOT NULL,
  STATUS          VARCHAR2(50) DEFAULT 'EM_PREPARO',
  OBSERVACAO      VARCHAR2(500),
  DATA_HORA       TIMESTAMP DEFAULT SYSTIMESTAMP,
  TOTAL           NUMBER(12,2) DEFAULT 0
);

CREATE TABLE PEDIDO_ITEM (
  ID_PEDIDO_ITEM     NUMBER PRIMARY KEY,
  PEDIDO_ID          NUMBER NOT NULL,
  ITEM_CARDAPIO_ID   NUMBER NOT NULL,
  QUANTIDADE         NUMBER(5) NOT NULL,
  PRECO_UNITARIO     NUMBER(10,2) NOT NULL,
  SUBTOTAL           NUMBER(12,2) NOT NULL,
  CONSTRAINT FK_PEDIDO FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID_PEDIDO) ON DELETE CASCADE,
  CONSTRAINT FK_ITEM FOREIGN KEY (ITEM_CARDAPIO_ID) REFERENCES ITEM_CARDAPIO(ID_ITEM)
);

-- ===================================================
-- TRIGGERS (auto incremento via sequence)
-- ====================================================

CREATE OR REPLACE TRIGGER TRG_ITEM_CARDAPIO_ID
BEFORE INSERT ON ITEM_CARDAPIO
FOR EACH ROW
WHEN (NEW.ID_ITEM IS NULL)
BEGIN
  SELECT ITEM_CARDAPIO_SEQ.NEXTVAL INTO :NEW.ID_ITEM FROM dual;
END;
/

CREATE OR REPLACE TRIGGER TRG_PEDIDO_ID
BEFORE INSERT ON PEDIDO
FOR EACH ROW
WHEN (NEW.ID_PEDIDO IS NULL)
BEGIN
  SELECT PEDIDO_SEQ.NEXTVAL INTO :NEW.ID_PEDIDO FROM dual;
END;
/

CREATE OR REPLACE TRIGGER TRG_PEDIDO_ITEM_ID
BEFORE INSERT ON PEDIDO_ITEM
FOR EACH ROW
WHEN (NEW.ID_PEDIDO_ITEM IS NULL)
BEGIN
  SELECT PEDIDO_ITEM_SEQ.NEXTVAL INTO :NEW.ID_PEDIDO_ITEM FROM dual;
END;
/

-- ====================================================
-- DADOS DE EXEMPLO
-- ====================================================

-- Itens do cardápio
INSERT INTO ITEM_CARDAPIO (NOME, DESCRICAO, PRECO, CATEGORIA, DISPONIVEL, IMAGEM_URL)
VALUES ('Pizza Calabresa', 'Deliciosa pizza com calabresa', 35.00, 'PRATO', 1, NULL);

INSERT INTO ITEM_CARDAPIO (NOME, DESCRICAO, PRECO, CATEGORIA, DISPONIVEL, IMAGEM_URL)
VALUES ('Refrigerante', 'Coca Cola 350ml', 8.50, 'BEBIDA', 1, NULL);

INSERT INTO ITEM_CARDAPIO (NOME, DESCRICAO, PRECO, CATEGORIA, DISPONIVEL, IMAGEM_URL)
VALUES ('Sorvete Chocolate', 'Sobremesa gelada', 12.00, 'SOBREMESA', 1, NULL);

INSERT INTO ITEM_CARDAPIO (NOME, DESCRICAO, PRECO, CATEGORIA, DISPONIVEL, IMAGEM_URL)
VALUES ('Pizza Mussarela', 'Pizza de mussarela com borda recheada', 38.00, 'PRATO', 1, NULL);

INSERT INTO ITEM_CARDAPIO (NOME, DESCRICAO, PRECO, CATEGORIA, DISPONIVEL, IMAGEM_URL)
VALUES ('Pizza Frango', 'Pizza de frango com catupiry', 40.00, 'PRATO', 1, NULL);

INSERT INTO ITEM_CARDAPIO (NOME, DESCRICAO, PRECO, CATEGORIA, DISPONIVEL, IMAGEM_URL)
VALUES ('Suco Laranja', 'Suco natural 300ml', 7.50, 'BEBIDA', 1, NULL);

INSERT INTO ITEM_CARDAPIO (NOME, DESCRICAO, PRECO, CATEGORIA, DISPONIVEL, IMAGEM_URL)
VALUES ('Salada Caesar', 'Salada com alface, frango e molho caesar', 25.00, 'PRATO', 1, NULL);

INSERT INTO ITEM_CARDAPIO (NOME, DESCRICAO, PRECO, CATEGORIA, DISPONIVEL, IMAGEM_URL)
VALUES ('Brownie', 'Brownie de chocolate com nozes', 10.00, 'SOBREMESA', 1, NULL);

INSERT INTO ITEM_CARDAPIO (NOME, DESCRICAO, PRECO, CATEGORIA, DISPONIVEL, IMAGEM_URL)
VALUES ('Água Mineral', 'Água sem gás 500ml', 5.00, 'BEBIDA', 1, NULL);

INSERT INTO ITEM_CARDAPIO (NOME, DESCRICAO, PRECO, CATEGORIA, DISPONIVEL, IMAGEM_URL)
VALUES ('Pizza Portuguesa', 'Pizza com presunto, ovos e azeitonas', 42.00, 'PRATO', 1, NULL);

-- Pedidos
INSERT INTO PEDIDO (ID_COMANDA, STATUS, OBSERVACAO, TOTAL)
VALUES (1001, 'EM_PREPARO', 'Sem queijo ralado', 35.00);

INSERT INTO PEDIDO (ID_COMANDA, STATUS, OBSERVACAO, TOTAL)
VALUES (1002, 'PRONTO', 'Um com gelo, outro sem', 17.00);

INSERT INTO PEDIDO (ID_COMANDA, STATUS, OBSERVACAO, TOTAL)
VALUES (1003, 'EM_PREPARO', 'Sem cebola', 45.00);

-- Itens dos pedidos
INSERT INTO PEDIDO_ITEM (PEDIDO_ID, ITEM_CARDAPIO_ID, QUANTIDADE, PRECO_UNITARIO, SUBTOTAL)
VALUES (1, 1, 1, 35.00, 35.00);

INSERT INTO PEDIDO_ITEM (PEDIDO_ID, ITEM_CARDAPIO_ID, QUANTIDADE, PRECO_UNITARIO, SUBTOTAL)
VALUES (2, 2, 2, 8.50, 17.00);

INSERT INTO PEDIDO_ITEM (PEDIDO_ID, ITEM_CARDAPIO_ID, QUANTIDADE, PRECO_UNITARIO, SUBTOTAL)
VALUES (3, 5, 1, 40.00, 40.00);

COMMIT;
